# pytorch fundamentals

this notebook introduces pytorch concepts needed to implement a gpt-style langauge model from scratch.

In [2]:
import sys
import platform
import torch

print("python version:", sys.version.split()[0])
print("python executable:", sys.executable)
print("pytorch version:", torch.__version__)
print("macOS version:", platform.mac_ver()[0])

python version: 3.11.16
python executable: /Users/nabigchaudhry/Projects/build-llm-from-scratch/.venv/bin/python
pytorch version: 2.13.0
macOS version: 26.6.2


In [3]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("selected device:", device)

selected device: mps


In [6]:
# create tensors

scalar = torch.tensor(7)

vector = torch.tensor([1.0, 2.0, 3.0])

matrix = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0],
])

print("scalar:", scalar)
print("scalar dimensions:", scalar.ndim)
print("scalar shape:", scalar.shape)

print("\nvector:", vector)
print("vector dimensions:", vector.ndim)
print("vector shape:", vector.shape)

print("\nmatrix:")
print(matrix)
print("matrix dimensions:", matrix.ndim)
print("matrix shape:", matrix.shape)

scalar: tensor(7)
scalar dimensions: 0
scalar shape: torch.Size([])

vector: tensor([1., 2., 3.])
vector dimensions: 1
vector shape: torch.Size([3])

matrix:
tensor([[1., 2.],
        [3., 4.]])
matrix dimensions: 2
matrix shape: torch.Size([2, 2])


In [8]:
# compare two kinds of multiplication

a = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0],
])

b = torch.tensor([
    [5.0, 6.0],
    [7.0, 8.0],
])

elementwise_result = a * b
matrix_result = a @ b

print("element-wise multiplication:")
print(elementwise_result)

print("\nmatrix multiplication:")
print(matrix_result)

element-wise multiplication:
tensor([[ 5., 12.],
        [21., 32.]])

matrix multiplication:
tensor([[19., 22.],
        [43., 50.]])


In [10]:
# move tensors to selected device

a_device = a.to(device)
b_device = b.to(device)

result_device = a_device @ b_device

print ("tensor device:", result_device.device)
print ("result:", result_device)

tensor device: mps:0
result: tensor([[19., 22.],
        [43., 50.]], device='mps:0')


In [12]:
# calculate the gradient automatically

x = torch.tensor(2.0, device=device, requires_grad=True)
y = x**2 + 3*x + 1

y.backward()

print("x:", x)
print("y:", y)
print("gradient of y with respect to x:", x.grad.item())

x: tensor(2., device='mps:0', requires_grad=True)
y: tensor(11., device='mps:0', grad_fn=<AddBackward0>)
gradient of y with respect to x: 7.0
